import PropTypes from "prop-types";

export interface MarginVerticalProps {
    default: string;
    sm: string;
    md: string;
    lg: string;
    xl: string;
}

export const MarginVerticalTypes = {
    /**
     * #### all media
     * Control the vertical margin of an element using the `my-{size}` utilities.
     */
    default: PropTypes.oneOf([
        '',
        'my-0',
        'my-1',
        'my-2',
        'my-3',
        'my-4',
        'my-5',
        'my-6',
        'my-8',
        'my-10',
        'my-12',
        'my-16',
        'my-20',
        'my-24',
        'my-32',
        'my-40',
        'my-48',
        'my-56',
        'my-64',
        'my-auto',
        'my-px',
        '-my-1',
        '-my-2',
        '-my-3',
        '-my-4',
        '-my-5',
        '-my-6',
        '-my-8',
        '-my-10',
        '-my-12',
        '-my-16',
        '-my-20',
        '-my-24',
        '-my-32',
        '-my-40',
        '-my-48',
        '-my-56',
        '-my-64',
        '-my-px',
    ]),
    /**
     *  #### @media (min-width: 640px)
     * Control the vertical margin of an element using the `my-{size}` utilities.
     */
    sm: PropTypes.oneOf([
        '',
        'my-0',
        'my-1',
        'my-2',
        'my-3',
        'my-4',
        'my-5',
        'my-6',
        'my-8',
        'my-10',
        'my-12',
        'my-16',
        'my-20',
        'my-24',
        'my-32',
        'my-40',
        'my-48',
        'my-56',
        'my-64',
        'my-auto',
        'my-px',
        '-my-1',
        '-my-2',
        '-my-3',
        '-my-4',
        '-my-5',
        '-my-6',
        '-my-8',
        '-my-10',
        '-my-12',
        '-my-16',
        '-my-20',
        '-my-24',
        '-my-32',
        '-my-40',
        '-my-48',
        '-my-56',
        '-my-64',
        '-my-px',
    ]),
    /**
     * #### @media (min-width: 768px)
     * Control the vertical margin of an element using the `my-{size}` utilities.
     */
    md: PropTypes.oneOf([
        '',
        'my-0',
        'my-1',
        'my-2',
        'my-3',
        'my-4',
        'my-5',
        'my-6',
        'my-8',
        'my-10',
        'my-12',
        'my-16',
        'my-20',
        'my-24',
        'my-32',
        'my-40',
        'my-48',
        'my-56',
        'my-64',
        'my-auto',
        'my-px',
        '-my-1',
        '-my-2',
        '-my-3',
        '-my-4',
        '-my-5',
        '-my-6',
        '-my-8',
        '-my-10',
        '-my-12',
        '-my-16',
        '-my-20',
        '-my-24',
        '-my-32',
        '-my-40',
        '-my-48',
        '-my-56',
        '-my-64',
        '-my-px',
    ]),
    /**
     * #### @media (min-width: 1024px)
     * Control the vertical margin of an element using the `my-{size}` utilities.
     */
    lg: PropTypes.oneOf([
        '',
        'my-0',
        'my-1',
        'my-2',
        'my-3',
        'my-4',
        'my-5',
        'my-6',
        'my-8',
        'my-10',
        'my-12',
        'my-16',
        'my-20',
        'my-24',
        'my-32',
        'my-40',
        'my-48',
        'my-56',
        'my-64',
        'my-auto',
        'my-px',
        '-my-1',
        '-my-2',
        '-my-3',
        '-my-4',
        '-my-5',
        '-my-6',
        '-my-8',
        '-my-10',
        '-my-12',
        '-my-16',
        '-my-20',
        '-my-24',
        '-my-32',
        '-my-40',
        '-my-48',
        '-my-56',
        '-my-64',
        '-my-px',
    ]),
    /**
     * #### @media (min-width: 1280px)
     * Control the vertical margin of an element using the `my-{size}` utilities.
     */
    xl: PropTypes.oneOf([
        '',
        'my-0',
        'my-1',
        'my-2',
        'my-3',
        'my-4',
        'my-5',
        'my-6',
        'my-8',
        'my-10',
        'my-12',
        'my-16',
        'my-20',
        'my-24',
        'my-32',
        'my-40',
        'my-48',
        'my-56',
        'my-64',
        'my-auto',
        'my-px',
        '-my-1',
        '-my-2',
        '-my-3',
        '-my-4',
        '-my-5',
        '-my-6',
        '-my-8',
        '-my-10',
        '-my-12',
        '-my-16',
        '-my-20',
        '-my-24',
        '-my-32',
        '-my-40',
        '-my-48',
        '-my-56',
        '-my-64',
        '-my-px',
    ]),
};
