import PropTypes from "prop-types";

export interface MarginHorizontalProps {
    default: string;
    sm: string;
    md: string;
    lg: string;
    xl: string;
}

export const MarginHorizontalTypes = {
    /**
     * #### all media
     * Control the horizontal margin of an element using the `mx-{size}` utilities.
     */
    default: PropTypes.oneOf([
        '',
        'mx-0',
        'mx-1',
        'mx-2',
        'mx-3',
        'mx-4',
        'mx-5',
        'mx-6',
        'mx-8',
        'mx-10',
        'mx-12',
        'mx-16',
        'mx-20',
        'mx-24',
        'mx-32',
        'mx-40',
        'mx-48',
        'mx-56',
        'mx-64',
        'mx-auto',
        'mx-px',
        '-mx-1',
        '-mx-2',
        '-mx-3',
        '-mx-4',
        '-mx-5',
        '-mx-6',
        '-mx-8',
        '-mx-10',
        '-mx-12',
        '-mx-16',
        '-mx-20',
        '-mx-24',
        '-mx-32',
        '-mx-40',
        '-mx-48',
        '-mx-56',
        '-mx-64',
        '-mx-px',
    ]),
    /**
     *  #### @media (min-width: 640px)
     * Control the horizontal margin of an element using the `mx-{size}` utilities.
     */
    sm: PropTypes.oneOf([
        '',
        'mx-0',
        'mx-1',
        'mx-2',
        'mx-3',
        'mx-4',
        'mx-5',
        'mx-6',
        'mx-8',
        'mx-10',
        'mx-12',
        'mx-16',
        'mx-20',
        'mx-24',
        'mx-32',
        'mx-40',
        'mx-48',
        'mx-56',
        'mx-64',
        'mx-auto',
        'mx-px',
        '-mx-1',
        '-mx-2',
        '-mx-3',
        '-mx-4',
        '-mx-5',
        '-mx-6',
        '-mx-8',
        '-mx-10',
        '-mx-12',
        '-mx-16',
        '-mx-20',
        '-mx-24',
        '-mx-32',
        '-mx-40',
        '-mx-48',
        '-mx-56',
        '-mx-64',
        '-mx-px',
    ]),
    /**
     * #### @media (min-width: 768px)
     * Control the horizontal margin of an element using the `mx-{size}` utilities.
     */
    md: PropTypes.oneOf([
        '',
        'mx-0',
        'mx-1',
        'mx-2',
        'mx-3',
        'mx-4',
        'mx-5',
        'mx-6',
        'mx-8',
        'mx-10',
        'mx-12',
        'mx-16',
        'mx-20',
        'mx-24',
        'mx-32',
        'mx-40',
        'mx-48',
        'mx-56',
        'mx-64',
        'mx-auto',
        'mx-px',
        '-mx-1',
        '-mx-2',
        '-mx-3',
        '-mx-4',
        '-mx-5',
        '-mx-6',
        '-mx-8',
        '-mx-10',
        '-mx-12',
        '-mx-16',
        '-mx-20',
        '-mx-24',
        '-mx-32',
        '-mx-40',
        '-mx-48',
        '-mx-56',
        '-mx-64',
        '-mx-px',
    ]),
    /**
     * #### @media (min-width: 1024px)
     * Control the horizontal margin of an element using the `mx-{size}` utilities.
     */
    lg: PropTypes.oneOf([
        '',
        'mx-0',
        'mx-1',
        'mx-2',
        'mx-3',
        'mx-4',
        'mx-5',
        'mx-6',
        'mx-8',
        'mx-10',
        'mx-12',
        'mx-16',
        'mx-20',
        'mx-24',
        'mx-32',
        'mx-40',
        'mx-48',
        'mx-56',
        'mx-64',
        'mx-auto',
        'mx-px',
        '-mx-1',
        '-mx-2',
        '-mx-3',
        '-mx-4',
        '-mx-5',
        '-mx-6',
        '-mx-8',
        '-mx-10',
        '-mx-12',
        '-mx-16',
        '-mx-20',
        '-mx-24',
        '-mx-32',
        '-mx-40',
        '-mx-48',
        '-mx-56',
        '-mx-64',
        '-mx-px',
    ]),
    /**
     * #### @media (min-width: 1280px)
     * Control the horizontal margin of an element using the `mx-{size}` utilities.
     */
    xl: PropTypes.oneOf([
        '',
        'mx-0',
        'mx-1',
        'mx-2',
        'mx-3',
        'mx-4',
        'mx-5',
        'mx-6',
        'mx-8',
        'mx-10',
        'mx-12',
        'mx-16',
        'mx-20',
        'mx-24',
        'mx-32',
        'mx-40',
        'mx-48',
        'mx-56',
        'mx-64',
        'mx-auto',
        'mx-px',
        '-mx-1',
        '-mx-2',
        '-mx-3',
        '-mx-4',
        '-mx-5',
        '-mx-6',
        '-mx-8',
        '-mx-10',
        '-mx-12',
        '-mx-16',
        '-mx-20',
        '-mx-24',
        '-mx-32',
        '-mx-40',
        '-mx-48',
        '-mx-56',
        '-mx-64',
        '-mx-px',
    ]),
};
