import PropTypes from "prop-types";

export interface MarginRightProps {
    default: string;
    sm: string;
    md: string;
    lg: string;
    xl: string;
}

export const MarginRightTypes = {
    /**
     * #### all media
     * Control the margin on one side of an element using the `m{t|r|b|l}-{size}` utilities.
     *
     * For example, mt-6 would add 1.5rem of margin to the top of an element,
     * mr-4 would add 1rem of margin to the right of an element,
     * mb-8 would add 2rem of margin to the bottom of an element,
     * and ml-2 would add 0.5rem of margin to the left of an element.
     */
    default: PropTypes.oneOf([
        '',
        'mr-0',
        'mr-1',
        'mr-2',
        'mr-3',
        'mr-4',
        'mr-5',
        'mr-6',
        'mr-8',
        'mr-10',
        'mr-12',
        'mr-16',
        'mr-20',
        'mr-24',
        'mr-32',
        'mr-40',
        'mr-48',
        'mr-56',
        'mr-64',
        'mr-auto',
        'mr-px',
        '-mr-1',
        '-mr-2',
        '-mr-3',
        '-mr-4',
        '-mr-5',
        '-mr-6',
        '-mr-8',
        '-mr-10',
        '-mr-12',
        '-mr-16',
        '-mr-20',
        '-mr-24',
        '-mr-32',
        '-mr-40',
        '-mr-48',
        '-mr-56',
        '-mr-64',
        '-mr-px',
    ]),
    /**
     *  #### @media (min-width: 640px)
     * Control the margin on one side of an element using the `m{t|r|b|l}-{size}` utilities.
     *
     * For example, mt-6 would add 1.5rem of margin to the top of an element,
     * mr-4 would add 1rem of margin to the right of an element,
     * mb-8 would add 2rem of margin to the bottom of an element,
     * and ml-2 would add 0.5rem of margin to the left of an element.
     */
    sm: PropTypes.oneOf([
        '',
        'mr-0',
        'mr-1',
        'mr-2',
        'mr-3',
        'mr-4',
        'mr-5',
        'mr-6',
        'mr-8',
        'mr-10',
        'mr-12',
        'mr-16',
        'mr-20',
        'mr-24',
        'mr-32',
        'mr-40',
        'mr-48',
        'mr-56',
        'mr-64',
        'mr-auto',
        'mr-px',
        '-mr-1',
        '-mr-2',
        '-mr-3',
        '-mr-4',
        '-mr-5',
        '-mr-6',
        '-mr-8',
        '-mr-10',
        '-mr-12',
        '-mr-16',
        '-mr-20',
        '-mr-24',
        '-mr-32',
        '-mr-40',
        '-mr-48',
        '-mr-56',
        '-mr-64',
        '-mr-px',
    ]),
    /**
     * #### @media (min-width: 768px)
     * Control the margin on one side of an element using the `m{t|r|b|l}-{size}` utilities.
     *
     * For example, mt-6 would add 1.5rem of margin to the top of an element,
     * mr-4 would add 1rem of margin to the right of an element,
     * mb-8 would add 2rem of margin to the bottom of an element,
     * and ml-2 would add 0.5rem of margin to the left of an element.
     */
    md: PropTypes.oneOf([
        '',
        'mr-0',
        'mr-1',
        'mr-2',
        'mr-3',
        'mr-4',
        'mr-5',
        'mr-6',
        'mr-8',
        'mr-10',
        'mr-12',
        'mr-16',
        'mr-20',
        'mr-24',
        'mr-32',
        'mr-40',
        'mr-48',
        'mr-56',
        'mr-64',
        'mr-auto',
        'mr-px',
        '-mr-1',
        '-mr-2',
        '-mr-3',
        '-mr-4',
        '-mr-5',
        '-mr-6',
        '-mr-8',
        '-mr-10',
        '-mr-12',
        '-mr-16',
        '-mr-20',
        '-mr-24',
        '-mr-32',
        '-mr-40',
        '-mr-48',
        '-mr-56',
        '-mr-64',
        '-mr-px',
    ]),
    /**
     * #### @media (min-width: 1024px)
     * Control the margin on one side of an element using the `m{t|r|b|l}-{size}` utilities.
     *
     * For example, mt-6 would add 1.5rem of margin to the top of an element,
     * mr-4 would add 1rem of margin to the right of an element,
     * mb-8 would add 2rem of margin to the bottom of an element,
     * and ml-2 would add 0.5rem of margin to the left of an element.
     */
    lg: PropTypes.oneOf([
        '',
        'mr-0',
        'mr-1',
        'mr-2',
        'mr-3',
        'mr-4',
        'mr-5',
        'mr-6',
        'mr-8',
        'mr-10',
        'mr-12',
        'mr-16',
        'mr-20',
        'mr-24',
        'mr-32',
        'mr-40',
        'mr-48',
        'mr-56',
        'mr-64',
        'mr-auto',
        'mr-px',
        '-mr-1',
        '-mr-2',
        '-mr-3',
        '-mr-4',
        '-mr-5',
        '-mr-6',
        '-mr-8',
        '-mr-10',
        '-mr-12',
        '-mr-16',
        '-mr-20',
        '-mr-24',
        '-mr-32',
        '-mr-40',
        '-mr-48',
        '-mr-56',
        '-mr-64',
        '-mr-px',
    ]),
    /**
     * #### @media (min-width: 1280px)
     * Control the margin on one side of an element using the `m{t|r|b|l}-{size}` utilities.
     *
     * For example, mt-6 would add 1.5rem of margin to the top of an element,
     * mr-4 would add 1rem of margin to the right of an element,
     * mb-8 would add 2rem of margin to the bottom of an element,
     * and ml-2 would add 0.5rem of margin to the left of an element.
     */
    xl: PropTypes.oneOf([
        '',
        'mr-0',
        'mr-1',
        'mr-2',
        'mr-3',
        'mr-4',
        'mr-5',
        'mr-6',
        'mr-8',
        'mr-10',
        'mr-12',
        'mr-16',
        'mr-20',
        'mr-24',
        'mr-32',
        'mr-40',
        'mr-48',
        'mr-56',
        'mr-64',
        'mr-auto',
        'mr-px',
        '-mr-1',
        '-mr-2',
        '-mr-3',
        '-mr-4',
        '-mr-5',
        '-mr-6',
        '-mr-8',
        '-mr-10',
        '-mr-12',
        '-mr-16',
        '-mr-20',
        '-mr-24',
        '-mr-32',
        '-mr-40',
        '-mr-48',
        '-mr-56',
        '-mr-64',
        '-mr-px',
    ]),
};
