import PropTypes from "prop-types";

export interface MarginProps {
    default: string;
    sm: string;
    md: string;
    lg: string;
    xl: string;
}

export const MarginTypes = {
    /**
     * #### all media
     * Control the margin on all sides of an element using the `m-{size}` utilities.
     */
    default: PropTypes.oneOf([
        '',
        'm-0',
        'm-1',
        'm-2',
        'm-3',
        'm-4',
        'm-5',
        'm-6',
        'm-8',
        'm-10',
        'm-12',
        'm-16',
        'm-20',
        'm-24',
        'm-32',
        'm-40',
        'm-48',
        'm-56',
        'm-64',
        'm-auto',
        'm-px',
        '-m-1',
        '-m-2',
        '-m-3',
        '-m-4',
        '-m-5',
        '-m-6',
        '-m-8',
        '-m-10',
        '-m-12',
        '-m-16',
        '-m-20',
        '-m-24',
        '-m-32',
        '-m-40',
        '-m-48',
        '-m-56',
        '-m-64',
        '-m-px',
    ]),
    /**
     *  #### @media (min-width: 640px)
     * Control the padding on all sides of an element using the `p-{size}` utilities.
     */
    sm: PropTypes.oneOf([
        '',
        'm-0',
        'm-1',
        'm-2',
        'm-3',
        'm-4',
        'm-5',
        'm-6',
        'm-8',
        'm-10',
        'm-12',
        'm-16',
        'm-20',
        'm-24',
        'm-32',
        'm-40',
        'm-48',
        'm-56',
        'm-64',
        'm-auto',
        'm-px',
        '-m-1',
        '-m-2',
        '-m-3',
        '-m-4',
        '-m-5',
        '-m-6',
        '-m-8',
        '-m-10',
        '-m-12',
        '-m-16',
        '-m-20',
        '-m-24',
        '-m-32',
        '-m-40',
        '-m-48',
        '-m-56',
        '-m-64',
        '-m-px',
    ]),
    /**
     * #### @media (min-width: 768px)
     * Control the padding on all sides of an element using the `p-{size}` utilities.
     */
    md: PropTypes.oneOf([
        '',
        'm-0',
        'm-1',
        'm-2',
        'm-3',
        'm-4',
        'm-5',
        'm-6',
        'm-8',
        'm-10',
        'm-12',
        'm-16',
        'm-20',
        'm-24',
        'm-32',
        'm-40',
        'm-48',
        'm-56',
        'm-64',
        'm-auto',
        'm-px',
        '-m-1',
        '-m-2',
        '-m-3',
        '-m-4',
        '-m-5',
        '-m-6',
        '-m-8',
        '-m-10',
        '-m-12',
        '-m-16',
        '-m-20',
        '-m-24',
        '-m-32',
        '-m-40',
        '-m-48',
        '-m-56',
        '-m-64',
        '-m-px',
    ]),
    /**
     * #### @media (min-width: 1024px)
     * Control the padding on all sides of an element using the `p-{size}` utilities.
     */
    lg: PropTypes.oneOf([
        '',
        'm-0',
        'm-1',
        'm-2',
        'm-3',
        'm-4',
        'm-5',
        'm-6',
        'm-8',
        'm-10',
        'm-12',
        'm-16',
        'm-20',
        'm-24',
        'm-32',
        'm-40',
        'm-48',
        'm-56',
        'm-64',
        'm-auto',
        'm-px',
        '-m-1',
        '-m-2',
        '-m-3',
        '-m-4',
        '-m-5',
        '-m-6',
        '-m-8',
        '-m-10',
        '-m-12',
        '-m-16',
        '-m-20',
        '-m-24',
        '-m-32',
        '-m-40',
        '-m-48',
        '-m-56',
        '-m-64',
        '-m-px',
    ]),
    /**
     * #### @media (min-width: 1280px)
     * Control the padding on all sides of an element using the `p-{size}` utilities.
     */
    xl: PropTypes.oneOf([
        '',
        'm-0',
        'm-1',
        'm-2',
        'm-3',
        'm-4',
        'm-5',
        'm-6',
        'm-8',
        'm-10',
        'm-12',
        'm-16',
        'm-20',
        'm-24',
        'm-32',
        'm-40',
        'm-48',
        'm-56',
        'm-64',
        'm-auto',
        'm-px',
        '-m-1',
        '-m-2',
        '-m-3',
        '-m-4',
        '-m-5',
        '-m-6',
        '-m-8',
        '-m-10',
        '-m-12',
        '-m-16',
        '-m-20',
        '-m-24',
        '-m-32',
        '-m-40',
        '-m-48',
        '-m-56',
        '-m-64',
        '-m-px',
    ]),
};
