import PropTypes from "prop-types";

export interface MarginTopProps {
    default: string;
    sm: string;
    md: string;
    lg: string;
    xl: string;
}

export const MarginTopTypes = {
    /**
     * #### all media
     * Control the margin on one side of an element using the `m{t|r|b|l}-{size}` utilities.
     *
     * For example, mt-6 would add 1.5rem of margin to the top of an element,
     * mr-4 would add 1rem of margin to the right of an element,
     * mb-8 would add 2rem of margin to the bottom of an element,
     * and ml-2 would add 0.5rem of margin to the left of an element.
     */
    default: PropTypes.oneOf([
        '',
        'mt-0',
        'mt-1',
        'mt-2',
        'mt-3',
        'mt-4',
        'mt-5',
        'mt-6',
        'mt-8',
        'mt-10',
        'mt-12',
        'mt-16',
        'mt-20',
        'mt-24',
        'mt-32',
        'mt-40',
        'mt-48',
        'mt-56',
        'mt-64',
        'mt-auto',
        'mt-px',
        '-mt-1',
        '-mt-2',
        '-mt-3',
        '-mt-4',
        '-mt-5',
        '-mt-6',
        '-mt-8',
        '-mt-10',
        '-mt-12',
        '-mt-16',
        '-mt-20',
        '-mt-24',
        '-mt-32',
        '-mt-40',
        '-mt-48',
        '-mt-56',
        '-mt-64',
        '-mt-px',
    ]),
    /**
     *  #### @media (min-width: 640px)
     * Control the margin on one side of an element using the `m{t|r|b|l}-{size}` utilities.
     *
     * For example, mt-6 would add 1.5rem of margin to the top of an element,
     * mr-4 would add 1rem of margin to the right of an element,
     * mb-8 would add 2rem of margin to the bottom of an element,
     * and ml-2 would add 0.5rem of margin to the left of an element.
     */
    sm: PropTypes.oneOf([
        '',
        'mt-0',
        'mt-1',
        'mt-2',
        'mt-3',
        'mt-4',
        'mt-5',
        'mt-6',
        'mt-8',
        'mt-10',
        'mt-12',
        'mt-16',
        'mt-20',
        'mt-24',
        'mt-32',
        'mt-40',
        'mt-48',
        'mt-56',
        'mt-64',
        'mt-auto',
        'mt-px',
        '-mt-1',
        '-mt-2',
        '-mt-3',
        '-mt-4',
        '-mt-5',
        '-mt-6',
        '-mt-8',
        '-mt-10',
        '-mt-12',
        '-mt-16',
        '-mt-20',
        '-mt-24',
        '-mt-32',
        '-mt-40',
        '-mt-48',
        '-mt-56',
        '-mt-64',
        '-mt-px',
    ]),
    /**
     * #### @media (min-width: 768px)
     * Control the margin on one side of an element using the `m{t|r|b|l}-{size}` utilities.
     *
     * For example, mt-6 would add 1.5rem of margin to the top of an element,
     * mr-4 would add 1rem of margin to the right of an element,
     * mb-8 would add 2rem of margin to the bottom of an element,
     * and ml-2 would add 0.5rem of margin to the left of an element.
     */
    md: PropTypes.oneOf([
        '',
        'mt-0',
        'mt-1',
        'mt-2',
        'mt-3',
        'mt-4',
        'mt-5',
        'mt-6',
        'mt-8',
        'mt-10',
        'mt-12',
        'mt-16',
        'mt-20',
        'mt-24',
        'mt-32',
        'mt-40',
        'mt-48',
        'mt-56',
        'mt-64',
        'mt-auto',
        'mt-px',
        '-mt-1',
        '-mt-2',
        '-mt-3',
        '-mt-4',
        '-mt-5',
        '-mt-6',
        '-mt-8',
        '-mt-10',
        '-mt-12',
        '-mt-16',
        '-mt-20',
        '-mt-24',
        '-mt-32',
        '-mt-40',
        '-mt-48',
        '-mt-56',
        '-mt-64',
        '-mt-px',
    ]),
    /**
     * #### @media (min-width: 1024px)
     * Control the margin on one side of an element using the `m{t|r|b|l}-{size}` utilities.
     *
     * For example, mt-6 would add 1.5rem of margin to the top of an element,
     * mr-4 would add 1rem of margin to the right of an element,
     * mb-8 would add 2rem of margin to the bottom of an element,
     * and ml-2 would add 0.5rem of margin to the left of an element.
     */
    lg: PropTypes.oneOf([
        '',
        'mt-0',
        'mt-1',
        'mt-2',
        'mt-3',
        'mt-4',
        'mt-5',
        'mt-6',
        'mt-8',
        'mt-10',
        'mt-12',
        'mt-16',
        'mt-20',
        'mt-24',
        'mt-32',
        'mt-40',
        'mt-48',
        'mt-56',
        'mt-64',
        'mt-auto',
        'mt-px',
        '-mt-1',
        '-mt-2',
        '-mt-3',
        '-mt-4',
        '-mt-5',
        '-mt-6',
        '-mt-8',
        '-mt-10',
        '-mt-12',
        '-mt-16',
        '-mt-20',
        '-mt-24',
        '-mt-32',
        '-mt-40',
        '-mt-48',
        '-mt-56',
        '-mt-64',
        '-mt-px',
    ]),
    /**
     * #### @media (min-width: 1280px)
     * Control the margin on one side of an element using the `m{t|r|b|l}-{size}` utilities.
     *
     * For example, mt-6 would add 1.5rem of margin to the top of an element,
     * mr-4 would add 1rem of margin to the right of an element,
     * mb-8 would add 2rem of margin to the bottom of an element,
     * and ml-2 would add 0.5rem of margin to the left of an element.
     */
    xl: PropTypes.oneOf([
        '',
        'mt-0',
        'mt-1',
        'mt-2',
        'mt-3',
        'mt-4',
        'mt-5',
        'mt-6',
        'mt-8',
        'mt-10',
        'mt-12',
        'mt-16',
        'mt-20',
        'mt-24',
        'mt-32',
        'mt-40',
        'mt-48',
        'mt-56',
        'mt-64',
        'mt-auto',
        'mt-px',
        '-mt-1',
        '-mt-2',
        '-mt-3',
        '-mt-4',
        '-mt-5',
        '-mt-6',
        '-mt-8',
        '-mt-10',
        '-mt-12',
        '-mt-16',
        '-mt-20',
        '-mt-24',
        '-mt-32',
        '-mt-40',
        '-mt-48',
        '-mt-56',
        '-mt-64',
        '-mt-px',
    ]),
};
